### PR TITLE
fix: some stats and text in the figure

### PR DESCRIPTION
**Pull request by AdrianM0**

### CODE REVIEW

**Comment by MrtinoRG** [comment]
If the podium is supposed to be accurate, the third position should be a model since Llama-405b scored 0.56

**Comment by MrtinoRG** [comment]
But overall the new figure looks really nice to me, thanks @AdrianM0

**Comment by AdrianM0** [comment]
@MrtinoRG nah, this is an illustration, we dont have to be accurate in it :D

**Review by MrtinoRG — APPROVED** [review]
Then lgtm

**Pull request merged**
