### PR TITLE
fix: update figure with the different tags

### PR DESCRIPTION
**Pull request by AdrianM0**

### CODE REVIEW

**Comment by AdrianM0** [comment]
@kjappelbaum can you suggest how many humans we have totally for this run? 

The old nr is 22, I think now there are more, right?

**Comment by kjappelbaum** [comment]
> @kjappelbaum can you suggest how many humans we have totally for this run?
> 
> The old nr is 22, I think now there are more, right?

Depends on which humans you count. In total, there have been 47 users.  22 with education info: 1 PhD, 2 PostDoc, 15 Master, 4 Bachelor

**Comment by AdrianM0** [comment]
> > @kjappelbaum can you suggest how many humans we have totally for this run?
> > The old nr is 22, I think now there are more, right?
> 
> Depends on which humans you count. In total, there have been 47 users. 22 with education info: 1 PhD, 2 PostDoc, 15 Master, 4 Bachelor
the nr that completed all questions is also 47?

**Comment by kjappelbaum** [comment]
> > > @kjappelbaum can you suggest how many humans we have totally for this run?
> > > The old nr is 22, I think now there are more, right?
> > 
> > 
> > Depends on which humans you count. In total, there have been 47 users. 22 with education info: 1 PhD, 2 PostDoc, 15 Master, 4 Bachelor
> 
> the nr that completed all questions is also 47?

17 if we count the people we use in the analysis (dropping people with less than 2 years' experience and who did not answer everything).

**Comment by kjappelbaum** [comment]
@AdrianM0 is this now with the latest numbers we discussed?

**Comment by AdrianM0** [comment]
> @AdrianM0 is this now with the latest numbers we discussed? 

yes

**Comment by kjappelbaum** [comment]
thx!

**Pull request merged**
